server:
  port: 8408

spring:
  application:
    name: casche-service

  cache:
    ehcache:
      config: ehcache.xml

  redis:
    password: redis
    clusters: 192.169.31.136:7001, 192.169.31.136:7002, 192.169.31.139:7003, 192.169.31.139:7004, 192.169.31.138:7005, 192.169.31.138:7006


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000 # 熔断超时时长：10000ms

eureka:
  client:
    service-url:
      defaultZone: http://192.168.248.128:8403/eureka


  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

