server:
  port: 8503
spring:
  application:
    name: page-service
  thymeleaf:
    cache: false

  #rabbitmq配置
  rabbitmq:
      host: 192.168.248.128
      username: legou
      password: legou
      virtual-host: /legou

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8403/eureka
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 10 #10秒不发送九过期
    lease-renewal-interval-in-seconds: 5 #每隔5秒发一次心跳
