server:
  port: 8504
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8403/eureka
    registry-fetch-interval-seconds: 10
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-expiration-duration-in-seconds: 10 #10秒不发送九过期
    lease-renewal-interval-in-seconds: 5 #每隔5秒发一次心跳




legou:
  jwt:
    secret: legou@Login(Auth}*^31)&heiMa% # 登录校验的密钥
    pubKeyPath: E:\myproject\upload\tmp\rsa.pub # 公钥地址
    priKeyPath: E:\myproject\upload\tmp\rsa.pri # 私钥地址
    expire: 30 # 过期时间,单位分钟
    cookieName: LG_TOKEN
    cookieMaxAge: 30