server:
  port: 8501

spring:
  application:
    name: item-service

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou?characterEncoding=UTF-8&useSSL=false
    username: root
    password: wangkf
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10

  redis:
      host: 192.168.248.128

  #rabbitmq配置
  rabbitmq:
      host: 192.168.248.128
      username: legou
      password: legou
      virtual-host: /legou
      template:
        retry:
          enabled: true
          multiplier: 2
          initial-interval: 10000ms
          max-interval: 210000ms
        exchange: legou.item.exchange
      publisher-confirms: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8403/eureka
    registry-fetch-interval-seconds: 5 #拉取订阅服务间隔时间
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true  #当你获取host时，返回的不是主机名，而是ip
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5  #心跳间隔时间
    lease-expiration-duration-in-seconds: 10  #心跳超时时间

ribbon:
  ConnectTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 1 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMillisecond: 10000

#sql在控制台打印便于调试找错
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

