server:
  port: 8405
spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 10MB # 限制文件上传的大小

# Eureka
eureka:
  client:
    service-url:
      #defaultZone: http://127.0.0.1:8403/eureka
      defaultZone: http://192.168.248.128:8403/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

#项目通用配置
lg:
  upload:
    baseUrl: http://image.legou.com/
    filePath: E:\myproject\upload
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp

#FastDFS
fdfs:
  so-timeout: 2500 #超时时间
  connect-timeout: 600 #连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 192.168.248.128:22122
